Refactor the main script
standupmaths/bubble-cosh pull request #1
Opened 2021-11-06 09:40 UTC by nfitzen

I was unsure what you intended with the `community` folder, so maybe this PR isn't in line with that. It certainly isn't a bug fix. I'm happy to move this improved script to the `community` folder if you want to retain authenticity from the video. (That said, I didn't change the algorithm, and I signed any comments I wrote with `-N`.)

The following is a list of stuff I did. Probably not exhaustive.

- Add type hints
- Add optional arguments
- Allow the file to be an importable module for further work (I just separated out the script portion).
- Use command line arguments
- Format with black
- File name uses underscores (necessary for importability)
- Add very simple testing
- Update README accordingly
- Use `break` in while loop

2021-11-07 20:02 UTC, oliverdunk requested changes
Hey @nfitzen! A big thank you for this. Lots of great tidy-up and probably some better Python (I don't think Matt would mind me saying that 😅). The honest answer is that we're still figuring out which PRs we should and shouldn't accept. Everything in here makes the code easier to use, though, so I think I'm happy with the idea of merging it.

I've left a few comments. Let me know when you've taken a look at those and I can give this another pass.

2021-11-07 20:02 UTC, oliverdunk commented on .gitignore
> +# SPDX-License-Identifier: MIT
Did you notice any files being generated that caused you to add this? I think we should go for a simple `.gitignore` with only files we expect to run in to.

2021-11-07 20:02 UTC, oliverdunk commented on README.md
> +<!-- SPDX-License-Identifier: MIT -->
Do you have an example of other projects that use an SPDX header? I'm not totally against it but it isn't something I've seen before.

2021-11-07 20:02 UTC, oliverdunk commented on LICENSE
> +Copyright (C) 2020-2021 standupmaths and the bubble-cosh contributors
Good spot, thanks!

2021-11-07 20:02 UTC, oliverdunk commented on bubble_cosh.py
> +# The type hints use syntax from Python 3.9+. See also PEP 585 -N
I think we can probably drop the `-N` in comments? You'll still get credit in the blame but the initialing is probably just confusing!

2021-11-07 20:02 UTC, oliverdunk commented on bubble_cosh.py
> +    custom_format = lambda prog: argparse.ArgumentDefaultsHelpFormatter(prog, width=72)
Am I understanding correctly that you did this to allow overriding the width? If so, maybe mentioning that would be a more helpful comment?

2021-11-11 04:42 UTC, nfitzen commented on .gitignore
> +# SPDX-License-Identifier: MIT
True. It was mostly the `__pycache__` folder.

2021-11-11 04:49 UTC, nfitzen commented on README.md
> +<!-- SPDX-License-Identifier: MIT -->
[Linux](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation) is the most notable project.
I know there are a few others, but regardless, it should be okay.

2021-11-11 04:55 UTC, nfitzen commented on bubble_cosh.py
> +# The type hints use syntax from Python 3.9+. See also PEP 585 -N
> You'll still get credit in the blame

I didn't do it for the credit; I was just making sure Matt's comments were marked as such (by omission). There's no issue with removing it, so I'm going to do that.

2021-11-11 05:07 UTC, nfitzen commented on bubble_cosh.py
> +    custom_format = lambda prog: argparse.ArgumentDefaultsHelpFormatter(prog, width=72)
I made a mention just now.

2021-11-11 05:12 UTC, nfitzen commented
> I've left a few comments. Let me know when you've taken a look at those and I can give this another pass.

@oliverdunk sounds good! I made the requested changes. Can you take a look?

2022-01-03 15:48 UTC, oliverdunk requested changes
Sorry for the slow reply! Left one more comment that would be nice to address before merging.

2022-01-03 15:48 UTC, oliverdunk commented on .gitignore
> +# Copyright (C) 2021 nfitzen
Where did these come from? I think if we need to add more copyright information, I would rather write our own gitignore from scratch so we don't need anything :)

2024-10-24 19:50 UTC, closed without merging